import { useEffect } from 'react';
import { Link } from 'react-router-dom';
import clsx from 'clsx';
import { Lightbulb, Lock, Server, Sparkles, Wand2 } from 'lucide-react';
import { useAuth } from '../../lib/auth';
import { useApi } from '../../lib/useApi';
import { useFe } from '../../fe/FeProvider';
import { Badge, Button, Card, CardHeader, PageHeader, Spinner } from '../../components/ui';

const IMPACT = { high: 'red', medium: 'amber', low: 'gray' };

// Both flags on this page are evaluated on the server by the Node SDK (Netlify Function).
export default function Insights() {
  const { user } = useAuth();
  const { env, version, recordDecision, track } = useFe();
  const { data, loading } = useApi('/insights', [user.plan, user.country, env, version]);

  useEffect(() => {
    if (!data) return;
    data.decisions.forEach((d) => recordDecision(d.key, d));
    if (data.insights.length) track('insight_viewed', { count: data.insights.length, model: data.model || 'none' });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [data]);

  if (loading && !data)
    return (
      <div className="grid h-96 place-items-center">
        <Spinner className="size-7" />
      </div>
    );

  const aiOn = data.insights.length > 0;
  return (
    <div>
      <PageHeader
        title="AI Insights"
        description="Lumen analyses your workspace and surfaces what changed, and what to do next."
        actions={
          <Badge color="violet">
            <Server className="size-3" /> Decided server-side · {data.env}
          </Badge>
        }
      />

      {aiOn ? (
        <Card>
          <CardHeader
            title="This week’s insights"
            description={`Generated by the ${data.model} model`}
            action={
              <Badge color="brand">
                <Sparkles className="size-3" /> {data.insights.length} insights
              </Badge>
            }
          />
          <ul className="divide-y divide-slate-100">
            {data.insights.map((i) => (
              <li key={i.title} className="flex gap-4 px-5 py-4 animate-fade-up">
                <div className="mt-0.5 grid size-9 shrink-0 place-items-center rounded-lg bg-brand-soft text-brand">
                  <Lightbulb className="size-4.5" />
                </div>
                <div className="flex-1">
                  <div className="flex flex-wrap items-center gap-2">
                    <p className="font-medium text-slate-900">{i.title}</p>
                    <Badge color={IMPACT[i.impact]}>{i.impact} impact</Badge>
                  </div>
                  <p className="mt-1 text-sm text-slate-600">{i.body}</p>
                </div>
              </li>
            ))}
          </ul>
        </Card>
      ) : (
        <Card className="relative overflow-hidden">
          <div className="pointer-events-none select-none space-y-3 p-6 opacity-40 blur-[3px]">
            {[1, 2, 3].map((n) => (
              <div key={n} className="flex gap-4">
                <div className="size-9 rounded-lg bg-slate-200" />
                <div className="flex-1 space-y-2">
                  <div className="h-3 w-2/3 rounded bg-slate-200" />
                  <div className="h-3 w-full rounded bg-slate-100" />
                </div>
              </div>
            ))}
          </div>
          <div className="absolute inset-0 grid place-items-center bg-white/40">
            <div className="max-w-sm text-center">
              <div className="mx-auto grid size-12 place-items-center rounded-full bg-slate-900 text-white">
                <Lock className="size-5" />
              </div>
              {user.plan === 'free' ? (
                <>
                  <h3 className="mt-4 font-semibold">AI Insights isn’t available on your plan yet</h3>
                  <p className="mt-1 text-sm text-slate-600">Upgrade to Pro to get weekly AI analysis of your product data.</p>
                  <Button to="/app/billing" className="mt-4">
                    Upgrade to Pro
                  </Button>
                </>
              ) : (
                <>
                  <h3 className="mt-4 font-semibold">AI Insights is rolling out gradually</h3>
                  <p className="mt-1 text-sm text-slate-600">Your workspace is on the list. You’ll get access automatically as the rollout expands.</p>
                </>
              )}
            </div>
          </div>
        </Card>
      )}

      <Card className="mt-6">
        <CardHeader
          title="Recommended next steps"
          description="Suggestions ranked for your workspace"
          action={<Badge color={data.algorithm === 'personalized' ? 'brand' : 'gray'}>algorithm: {data.algorithm}</Badge>}
        />
        <div className="grid gap-4 p-5 md:grid-cols-3">
          {data.recommendations.map((r) => (
            <div key={r.title} className={clsx('rounded-xl border p-4', data.algorithm === 'personalized' ? 'border-brand-ring bg-brand-soft/40' : 'border-slate-200')}>
              <Wand2 className="size-5 text-brand" />
              <p className="mt-3 text-sm font-semibold">{r.title}</p>
              <p className="mt-1 text-xs text-slate-500">{r.reason}</p>
            </div>
          ))}
        </div>
      </Card>

      <p className="mt-6 text-xs text-slate-400">
        Tip: open the FE Control Tower to see the server-side decisions for <code>ai_insights</code> and <code>smart_recommendations</code>, or visit the{' '}
        <Link to="/app/feature-lab" className="underline">
          Feature Lab
        </Link>
        .
      </p>
    </div>
  );
}
